import type { BRDResult } from './generate';

export function exportToMarkdown(brd: BRDResult): string {
  let md = `# ${brd.overview.projectName}\n\n`;
  md += `## Project Overview\n\n`;
  md += `**Description:** ${brd.overview.description}\n\n`;
  md += `**Target Users:** ${brd.overview.targetUsers}\n\n`;
  md += `**Business Value:** ${brd.overview.businessValue}\n\n`;

  md += `## Business Objectives\n\n`;
  brd.objectives?.forEach?.((obj: string) => { md += `- ${obj}\n`; });
  md += '\n';

  md += `## Functional Requirements\n\n`;
  md += `| # | Requirement | Description | Priority |\n`;
  md += `|---|-------------|-------------|----------|\n`;
  brd.functionalRequirements?.forEach?.((req: any, i: number) => {
    md += `| ${i + 1} | ${req.name} | ${req.description} | ${req.priority} |\n`;
  });
  md += '\n';

  md += `## Non-Functional Requirements\n\n`;
  md += `| # | Requirement | Category | Description |\n`;
  md += `|---|------------|----------|-------------|\n`;
  brd.nonFunctionalRequirements?.forEach?.((req: any, i: number) => {
    md += `| ${i + 1} | ${req.name} | ${req.category} | ${req.description} |\n`;
  });
  md += '\n';

  md += `## User Stories\n\n`;
  brd.userStories?.forEach?.((story: any) => {
    md += `### ${story.id}\n\n`;
    md += `${story.story}\n\n`;
    md += `**Acceptance Criteria:**\n`;
    story.acceptance?.forEach?.((acc: string) => { md += `- ${acc}\n`; });
    md += '\n';
  });

  md += `## User Roles\n\n`;
  md += `| Role | Description | Permissions |\n`;
  md += `|------|-------------|-------------|\n`;
  brd.userRoles?.forEach?.((role: any) => {
    md += `| ${role.role} | ${role.description} | ${role.permissions?.join(', ')} |\n`;
  });
  md += '\n';

  md += `## Architecture\n\n`;
  md += `**Components:**\n`;
  brd.architecture?.components?.forEach?.((comp: string) => { md += `- ${comp}\n`; });
  md += `\n**Data Flow:** ${brd.architecture?.dataFlow || ''}\n\n`;

  md += `## Technology Stack\n\n`;
  md += `| Layer | Technologies |\n`;
  md += `|-------|-------------|\n`;
  md += `| Frontend | ${brd.techStack?.frontend?.join(', ')} |\n`;
  md += `| Backend | ${brd.techStack?.backend?.join(', ')} |\n`;
  md += `| Database | ${brd.techStack?.database?.join(', ')} |\n`;
  md += `| Third Party | ${brd.techStack?.thirdParty?.join(', ')} |\n\n`;

  md += `## Project Timeline\n\n`;
  brd.timeline?.forEach?.((phase: any) => {
    md += `### ${phase.phase} (${phase.duration})\n\n`;
    phase.tasks?.forEach?.((task: string) => { md += `- ${task}\n`; });
    md += '\n';
  });

  md += `## Risk Analysis\n\n`;
  md += `| Risk | Impact | Mitigation |\n`;
  md += `|------|--------|------------|\n`;
  brd.riskAnalysis?.forEach?.((risk: any) => {
    md += `| ${risk.risk} | ${risk.impact} | ${risk.mitigation} |\n`;
  });
  md += '\n';

  md += `## Success Metrics\n\n`;
  md += `| Metric | Target |\n`;
  md += `|--------|--------|\n`;
  brd.successMetrics?.forEach?.((metric: any) => {
    md += `| ${metric.metric} | ${metric.target} |\n`;
  });
  md += '\n';

  md += `---\n*Generated by AutoBRD AI*\n`;

  return md;
}

export function downloadMarkdown(brd: BRDResult) {
  const md = exportToMarkdown(brd);
  downloadFile(md, `${brd.overview.projectName.replace(/\s+/g, '_')}_BRD.md`, 'text/markdown');
}

export function downloadPDF(brd: BRDResult) {
  // Generate a printable HTML that can be saved as PDF
  const html = generatePrintableHTML(brd);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const w = window.open(url, '_blank');
  if (w) {
    w.onload = () => {
      w.print();
    };
  }
}

export function downloadDOCX(brd: BRDResult) {
  // As a fallback, generate rich HTML that Word can open
  const html = generateDocxHTML(brd);
  downloadFile(html, `${brd.overview.projectName.replace(/\s+/g, '_')}_BRD.doc`, 'application/msword');
}

function generatePrintableHTML(brd: BRDResult): string {
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${brd.overview.projectName} - BRD</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; }
  h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 8px; }
  h2 { color: #1e40af; margin-top: 32px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th, td { border: 1px solid #d1d5db; padding: 8px 12px; text-align: left; }
  th { background: #eff6ff; color: #1e40af; font-weight: 600; }
  .high { color: #dc2626; font-weight: 600; }
  .medium { color: #d97706; }
  .low { color: #059669; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #d1d5db; color: #6b7280; font-size: 12px; }
</style></head><body>
${generateBRDContent(brd)}
<div class="footer">Generated by AutoBRD AI</div>
</body></html>`;
}

function generateDocxHTML(brd: BRDResult): string {
  return `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head><meta charset="utf-8"><title>${brd.overview.projectName}</title>
<style>
  body { font-family: Calibri, Arial, sans-serif; font-size: 11pt; color: #333; }
  h1 { font-size: 24pt; color: #1e3a8a; }
  h2 { font-size: 16pt; color: #1e40af; margin-top: 24pt; }
  table { border-collapse: collapse; width: 100%; }
  th { background: #dbeafe; border: 1px solid #93c5fd; padding: 6pt; font-size: 10pt; }
  td { border: 1px solid #d1d5db; padding: 6pt; font-size: 10pt; }
</style></head><body>
${generateBRDContent(brd)}
<br/><p style="color:#6b7280;font-size:9pt;">Generated by AutoBRD AI</p>
</body></html>`;
}

function generateBRDContent(brd: BRDResult): string {
  let html = `<h1>${brd.overview.projectName}</h1>`;
  html += `<h2>Project Overview</h2>`;
  html += `<p><strong>Description:</strong> ${brd.overview.description}</p>`;
  html += `<p><strong>Target Users:</strong> ${brd.overview.targetUsers}</p>`;
  html += `<p><strong>Business Value:</strong> ${brd.overview.businessValue}</p>`;

  if (brd.objectives?.length) {
    html += `<h2>Business Objectives</h2><ul>`;
    brd.objectives.forEach(o => { html += `<li>${o}</li>`; });
    html += `</ul>`;
  }

  html += `<h2>Functional Requirements</h2><table><tr><th>#</th><th>Requirement</th><th>Description</th><th>Priority</th></tr>`;
  brd.functionalRequirements?.forEach?.((r: any, i: number) => {
    html += `<tr><td>${i + 1}</td><td>${r.name}</td><td>${r.description}</td><td class="${r.priority?.toLowerCase()}">${r.priority}</td></tr>`;
  });
  html += `</table>`;

  html += `<h2>Non-Functional Requirements</h2><table><tr><th>#</th><th>Requirement</th><th>Category</th><th>Description</th></tr>`;
  brd.nonFunctionalRequirements?.forEach?.((r: any, i: number) => {
    html += `<tr><td>${i + 1}</td><td>${r.name}</td><td>${r.category}</td><td>${r.description}</td></tr>`;
  });
  html += `</table>`;

  html += `<h2>User Stories</h2>`;
  brd.userStories?.forEach?.((s: any) => {
    html += `<h3>${s.id}</h3><p>${s.story}</p><p><strong>Acceptance Criteria:</strong></p><ul>`;
    s.acceptance?.forEach?.((a: string) => { html += `<li>${a}</li>`; });
    html += `</ul>`;
  });

  html += `<h2>User Roles</h2><table><tr><th>Role</th><th>Description</th><th>Permissions</th></tr>`;
  brd.userRoles?.forEach?.((r: any) => {
    html += `<tr><td>${r.role}</td><td>${r.description}</td><td>${r.permissions?.join(', ')}</td></tr>`;
  });
  html += `</table>`;

  html += `<h2>Architecture</h2><p><strong>Components:</strong></p><ul>`;
  brd.architecture?.components?.forEach?.((c: string) => { html += `<li>${c}</li>`; });
  html += `</ul><p><strong>Data Flow:</strong> ${brd.architecture?.dataFlow || ''}</p>`;

  html += `<h2>Technology Stack</h2><table><tr><th>Layer</th><th>Technologies</th></tr>`;
  html += `<tr><td>Frontend</td><td>${brd.techStack?.frontend?.join(', ')}</td></tr>`;
  html += `<tr><td>Backend</td><td>${brd.techStack?.backend?.join(', ')}</td></tr>`;
  html += `<tr><td>Database</td><td>${brd.techStack?.database?.join(', ')}</td></tr>`;
  html += `<tr><td>Third Party</td><td>${brd.techStack?.thirdParty?.join(', ')}</td></tr></table>`;

  html += `<h2>Project Timeline</h2>`;
  brd.timeline?.forEach?.((p: any) => {
    html += `<h3>${p.phase} (${p.duration})</h3><ul>`;
    p.tasks?.forEach?.((t: string) => { html += `<li>${t}</li>`; });
    html += `</ul>`;
  });

  html += `<h2>Risk Analysis</h2><table><tr><th>Risk</th><th>Impact</th><th>Mitigation</th></tr>`;
  brd.riskAnalysis?.forEach?.((r: any) => {
    html += `<tr><td>${r.risk}</td><td class="${r.impact?.toLowerCase()}">${r.impact}</td><td>${r.mitigation}</td></tr>`;
  });
  html += `</table>`;

  html += `<h2>Success Metrics</h2><table><tr><th>Metric</th><th>Target</th></tr>`;
  brd.successMetrics?.forEach?.((m: any) => {
    html += `<tr><td>${m.metric}</td><td>${m.target}</td></tr>`;
  });
  html += `</table>`;

  return html;
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
